### ISSUE TITLE
Условия для бинарного поиска

### ISSUE THREAD

**Issue by khda91** [pkev321/task_2#1]
https://github.com/pkev321/task_2/blob/15c1f319536a850e5ad54c9df23a25c5d86669a3/src/ru/levelup/pavel_kustov/qa/homework1/task2/Main.java#L54

Какое необходимое условие должно быть выполнено для массив, чтобы бинарный поиск работал корректно?

**Comment by pkev321** [comment]
Наверно - элемент который мы ищем должен быть внутри массива? 
(не очень понял вопрос)

**Comment by khda91** [comment]
Павел, не обязательно. Поиск может и не найти элемент в массив. 

https://github.com/pkev321/task_2/blob/15c1f319536a850e5ad54c9df23a25c5d86669a3/src/ru/levelup/pavel_kustov/qa/homework1/task2/Main.java#L14

Посмотрите, пожалуйста, на свой массив. Во всех ли случаях поиска заданного элемента, который находится в данном массиве, будет давать положительный результат?

**Comment by pkev321** [comment]
Понял.
Обязательно нужен отсортированный массив.
Удалил этот кусок кода во время чистки - внес правки теперь всё должно работать всегда

**Comment by khda91** [comment]
Павел, закрываю вопрос
